### ISSUE TITLE
Wrong schema/table/field names in DB2 UDB support

### ISSUE THREAD

**Issue by donnet** [flyway/flywaydb.org#29] opened 2014-09-24 11:00 UTC
Some queries are only working for DB2 UDB linux/windows version but not for DB2 AS/400 

eg: 
system schema is different (SYSIBM instead of SYSCAT, ...)
fields are different (SCHEMA_NAME instead of SCHEMANAME, ...)
field values are different (table type is 'BASE TABLE' instead of 'T')
...

I propose to commit some code to detect the right naming convention in function of the DB2 flavour

**Comment by axelfontaine** [comment] 2014-10-02 22:15
Duplicate of https://github.com/flyway/flyway/issues/105

**Closed as completed by axelfontaine** 2014-10-02 22:15 UTC
